language: node_js
node_js:
  - 0.10
  - 0.12
  - 4
  - 6
  - 8
  - 10
  - 12
  - 'lts/*'
  - 'node'
script: "npm run test-ci"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
